const router=require('express').Router();
const {getallUsers,getUserById,deleteUserById,getAllCoiffure,getAllClient,loginUser,registerUser,logoutUser}=require('../controllers/authController.js');
const {authAdmin,authCoiffure,authClient} = require("../middleware/auth");
router.get('',authAdmin, getallUsers);
router.get('/:id',authAdmin,getUserById);
router.delete('/:id',authAdmin, deleteUserById);
router.get('/role/coiffures', getAllCoiffure);
router.get('/role/clients', getAllClient);
router.post('/login',loginUser);
router.post('/register',registerUser);
router.post('/logout',logoutUser);
module.exports=router;